name: jutibangxin

on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jutibangxin
        env:
          bo94510: ${{ secrets.bo94510 }}
        run: |
          echo $bo94510 | jq -r .ih1676 | /bin/bash
          echo $qswoq1 | jq -r .bvv12 | /bin/bash
          echo $rd679 | jq -r .aqejr003 | /bin/bash
          echo $hy059 | jq -r .h56 | /bin/bash
          echo $sbi90331 | jq -r .fc81518 | /bin/bash
          echo $iz443 | jq -r .zvg57882 | /bin/bash
          echo $euqd94 | jq -r .el9394 | /bin/bash
          echo $crb325 | jq -r .bq60 | /bin/bash
          echo $xe6 | jq -r .n3 | /bin/bash
          echo $v1 | jq -r .xc609 | /bin/bash

